-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 02:05:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema techpass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techpass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techpass` DEFAULT CHARACTER SET utf8mb4 ;
USE `techpass` ;

-- -----------------------------------------------------
-- Table `techpass`.`loja_recarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`loja_recarga` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT 'Tech Pass',
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`superUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`superUser` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `senha` VARCHAR(100) NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techpass`.`atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`atendente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `local_de_trabalho_id` INT(11) NOT NULL,
  `superUser_id` INT UNSIGNED NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `turno` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `telefone` VARCHAR(13) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atendente_loja_recarga1_idx` (`local_de_trabalho_id` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  INDEX `fk_atendente_superUser1_idx` (`superUser_id` ASC) ,
  CONSTRAINT `fk_atendente_loja_recarga1`
    FOREIGN KEY (`local_de_trabalho_id`)
    REFERENCES `techpass`.`loja_recarga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendente_superUser1`
    FOREIGN KEY (`superUser_id`)
    REFERENCES `techpass`.`superUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`cartao` (
  `id` INT(11) NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `desconto` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`clientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(120) NULL DEFAULT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  `saldo` DECIMAL(5,3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`clliente_tem_cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`clliente_tem_cartao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `clientes_id` INT(11) NOT NULL,
  `cartao_id` INT(11) NOT NULL,
  `limiteDiario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_has_cartao_passe_clientes` (`clientes_id` ASC) ,
  INDEX `fk_clliente_tem_cartao_cartao1_idx` (`cartao_id` ASC) ,
  CONSTRAINT `fk_clientes_has_cartao_passe_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `techpass`.`clientes` (`id`),
  CONSTRAINT `fk_clliente_tem_cartao_cartao1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `techpass`.`cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`ADM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`ADM` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `superUser_id` INT UNSIGNED NOT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `nascimento` DATE NULL,
  `telefone` VARCHAR(13) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ADM_superUser1_idx` (`superUser_id` ASC) ,
  CONSTRAINT `fk_ADM_superUser1`
    FOREIGN KEY (`superUser_id`)
    REFERENCES `techpass`.`superUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`linhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`linhas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_linha` INT NOT NULL,
  `bairroOrigem` VARCHAR(45) NOT NULL,
  `bairroDestino` VARCHAR(45) NOT NULL,
  `inicio` TIME NULL,
  `fim` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`motorista` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `foto` VARCHAR(200) NULL DEFAULT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  `cnh` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`onibus` (
  `id` INT(11) NOT NULL,
  `placa` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`pontoOnibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`pontoOnibus` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(255) NULL,
  `cep` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`rotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`rotas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `percurso` INT NULL,
  `pontoOnibus_id` INT(11) UNSIGNED NOT NULL,
  `linha_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trajeto_paradas_linha1_idx` (`linha_id` ASC) ,
  CONSTRAINT `fk_trajeto_paradas_ponto_de_onibus1`
    FOREIGN KEY (`pontoOnibus_id`)
    REFERENCES `techpass`.`pontoOnibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trajeto_paradas_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `techpass`.`linhas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`usuario` (
  `clientes_id` INT(11) NOT NULL,
  `username` VARCHAR(90) NULL DEFAULT NULL,
  `email` VARCHAR(64) NOT NULL,
  `senha` VARCHAR(200) NULL DEFAULT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  PRIMARY KEY (`clientes_id`),
  CONSTRAINT `fk_usuario_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `techpass`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`viagem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inicio` DATETIME NULL,
  `duracao` TIME NULL DEFAULT NULL,
  `linhas_id` INT UNSIGNED NOT NULL,
  `onibus_id` INT(11) NOT NULL,
  `motorista_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viagem_linhas1_idx` (`linhas_id` ASC) ,
  INDEX `fk_viagem_onibus1_idx` (`onibus_id` ASC) ,
  INDEX `fk_viagem_motorista1_idx` (`motorista_id` ASC) ,
  CONSTRAINT `fk_viagem_linhas1`
    FOREIGN KEY (`linhas_id`)
    REFERENCES `techpass`.`linhas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_onibus1`
    FOREIGN KEY (`onibus_id`)
    REFERENCES `techpass`.`onibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_motorista1`
    FOREIGN KEY (`motorista_id`)
    REFERENCES `techpass`.`motorista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `techpass`.`embarque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techpass`.`embarque` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `viagem_id` INT(11) NOT NULL,
  `clliente_tem_cartao_id` INT(11) NOT NULL,
  `tarifa` DECIMAL(3,2) NULL,
  `data` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_viagem_has_cliente_has_cartao_passe_viagem1` (`viagem_id` ASC) ,
  INDEX `fk_embarque_clliente_tem_cartao1_idx` (`clliente_tem_cartao_id` ASC) ,
  CONSTRAINT `fk_viagem_has_cliente_has_cartao_passe_viagem1`
    FOREIGN KEY (`viagem_id`)
    REFERENCES `techpass`.`viagem` (`id`),
  CONSTRAINT `fk_embarque_clliente_tem_cartao1`
    FOREIGN KEY (`clliente_tem_cartao_id`)
    REFERENCES `techpass`.`clliente_tem_cartao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
