-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 01:14:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema projetointegrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetointegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetointegrador` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`onibus` (
  `id` INT NULL,
  `placa` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motorista` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `nascimento` DATE NOT NULL,
  `salario` INT NOT NULL,
  `telefone` INT NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartao-passe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao-passe` (
  `id` INT NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `desconto` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador`.`cliente` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `nascimento` DATE NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `cartao-passe_id` INT NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cliente_cartao-passe1_idx` (`cartao-passe_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_cartao-passe1`
    FOREIGN KEY (`cartao-passe_id`)
    REFERENCES `mydb`.`cartao-passe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` INT NULL,
  `token` VARCHAR(45) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `fk_usuario_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `projetointegrador`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estimavativaViagensAoDia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estimavativaViagensAoDia` (
  `id` INT NOT NULL,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idhorario-linha_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trajeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trajeto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enderecos` VARCHAR(85) NOT NULL,
  `percurso` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtrajeto_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador`.`linha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador`.`linha` (
  `id` INT NULL AUTO_INCREMENT,
  `numero-linha` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `trajeto_id` INT NOT NULL,
  `estimavativaViagensAoDia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero-linha_UNIQUE` (`numero-linha` ASC) VISIBLE,
  INDEX `fk_linhas_trajeto1_idx` (`trajeto_id` ASC) VISIBLE,
  INDEX `fk_linha_estimavativaViagensAoDia1_idx` (`estimavativaViagensAoDia_id` ASC) VISIBLE,
  CONSTRAINT `fk_linhas_trajeto1`
    FOREIGN KEY (`trajeto_id`)
    REFERENCES `mydb`.`trajeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linha_estimavativaViagensAoDia1`
    FOREIGN KEY (`estimavativaViagensAoDia_id`)
    REFERENCES `mydb`.`estimavativaViagensAoDia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viagem` (
  `idviagem` INT NOT NULL AUTO_INCREMENT,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  `onibus_id` INT NOT NULL,
  `motorista_registro` INT NOT NULL,
  `linha_id` INT NOT NULL,
  PRIMARY KEY (`idviagem`),
  INDEX `fk_viagem_onibus_idx` (`onibus_id` ASC) VISIBLE,
  INDEX `fk_viagem_motorista1_idx` (`motorista_registro` ASC) VISIBLE,
  INDEX `fk_viagem_linha1_idx` (`linha_id` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_onibus`
    FOREIGN KEY (`onibus_id`)
    REFERENCES `mydb`.`onibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_motorista1`
    FOREIGN KEY (`motorista_registro`)
    REFERENCES `mydb`.`motorista` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `projetointegrador`.`linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loja-Recarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja-Recarga` (
  `idLoja` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL DEFAULT 'Tech Pass',
  `cep` VARCHAR(8) NOT NULL,
  `coordenadas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viagem_has_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viagem_has_cliente` (
  `viagem_idviagem` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `entrada` DATETIME NOT NULL DEFAULT now(),
  `tarifa(5,2)` INT NOT NULL,
  PRIMARY KEY (`viagem_idviagem`, `cliente_id`),
  INDEX `fk_viagem_has_cliente_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_viagem_has_cliente_viagem1_idx` (`viagem_idviagem` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_has_cliente_viagem1`
    FOREIGN KEY (`viagem_idviagem`)
    REFERENCES `mydb`.`viagem` (`idviagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_has_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `projetointegrador`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `projetointegrador` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
