-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 22:44:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema projetointegrador
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`onibus` (
  `id` INT NULL,
  `placa` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motorista` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `nascimento` DATE NOT NULL,
  `salario` INT NOT NULL,
  `telefone` INT NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` INT NULL,
  `token` VARCHAR(45) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero-linha` INT NULL,
  `bairroIda` VARCHAR(45) NULL,
  `BairroVolta` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HorarioSaidaBairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HorarioSaidaBairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saida` DATETIME NULL,
  `bairroSaida` VARCHAR(45) NULL,
  `linha_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idhorario-linha_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_HorarioSaidaBairro_linha1_idx` (`linha_id` ASC) VISIBLE,
  CONSTRAINT `fk_HorarioSaidaBairro_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `mydb`.`linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viagem` (
  `idviagem` INT NOT NULL AUTO_INCREMENT,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  `onibus_id` INT NOT NULL,
  `motorista_registro` INT NOT NULL,
  `linha_id` INT NOT NULL,
  PRIMARY KEY (`idviagem`),
  INDEX `fk_viagem_onibus_idx` (`onibus_id` ASC) VISIBLE,
  INDEX `fk_viagem_motorista1_idx` (`motorista_registro` ASC) VISIBLE,
  INDEX `fk_viagem_linha1_idx` (`linha_id` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_onibus`
    FOREIGN KEY (`onibus_id`)
    REFERENCES `mydb`.`onibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_motorista1`
    FOREIGN KEY (`motorista_registro`)
    REFERENCES `mydb`.`motorista` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `mydb`.`linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loja-Recarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja-Recarga` (
  `idLoja` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL DEFAULT 'Tech Pass',
  `cep` VARCHAR(8) NOT NULL,
  `coordenadas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartao-passe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao-passe` (
  `id` INT NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `desconto` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atendente` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `salario` INT NULL,
  `senha` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gerente` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `salario` INT NULL,
  `senha` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`registro`),
  UNIQUE INDEX `cpg_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `saldo` DECIMAL(5,3) NULL,
  `cadastrado_cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_clientes_usuario1_idx` (`cadastrado_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_usuario1`
    FOREIGN KEY (`cadastrado_cliente`)
    REFERENCES `mydb`.`usuario` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes_has_cartao-passe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes_has_cartao-passe` (
  `clientes_id` INT NOT NULL,
  `cartao-passe_id` INT NOT NULL,
  PRIMARY KEY (`clientes_id`, `cartao-passe_id`),
  INDEX `fk_clientes_has_cartao-passe_cartao-passe1_idx` (`cartao-passe_id` ASC) VISIBLE,
  INDEX `fk_clientes_has_cartao-passe_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_has_cartao-passe_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `mydb`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_cartao-passe_cartao-passe1`
    FOREIGN KEY (`cartao-passe_id`)
    REFERENCES `mydb`.`cartao-passe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viagem_has_cliente/cartão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viagem_has_cliente/cartão` (
  `viagem_idviagem` INT NOT NULL,
  `clientes_has_cartao-passe_clientes_id` INT NOT NULL,
  `clientes_has_cartao-passe_cartao-passe_id` INT NOT NULL,
  `tarifa` DECIMAL(3,2) NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`viagem_idviagem`, `clientes_has_cartao-passe_clientes_id`, `clientes_has_cartao-passe_cartao-passe_id`),
  INDEX `fk_viagem_has_cliente_has_cartao-passe_viagem1_idx` (`viagem_idviagem` ASC) VISIBLE,
  INDEX `fk_viagem_has_cliente/cartão_clientes_has_cartao-passe1_idx` (`clientes_has_cartao-passe_clientes_id` ASC, `clientes_has_cartao-passe_cartao-passe_id` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_has_cliente_has_cartao-passe_viagem1`
    FOREIGN KEY (`viagem_idviagem`)
    REFERENCES `mydb`.`viagem` (`idviagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_has_cliente/cartão_clientes_has_cartao-passe1`
    FOREIGN KEY (`clientes_has_cartao-passe_clientes_id` , `clientes_has_cartao-passe_cartao-passe_id`)
    REFERENCES `mydb`.`clientes_has_cartao-passe` (`clientes_id` , `cartao-passe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ponto_de_onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ponto_de_onibus` (
  `id` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trajeto_paradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trajeto_paradas` (
  `linha_id` INT NOT NULL,
  `ponto_de_onibus_id` INT NOT NULL,
  `bairroSaida` VARCHAR(25) NOT NULL,
  `caminho` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`linha_id`, `ponto_de_onibus_id`),
  INDEX `fk_linha_has_ponto_de_onibus_ponto_de_onibus1_idx` (`ponto_de_onibus_id` ASC) VISIBLE,
  INDEX `fk_linha_has_ponto_de_onibus_linha1_idx` (`linha_id` ASC) VISIBLE,
  CONSTRAINT `fk_linha_has_ponto_de_onibus_linha1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `mydb`.`linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linha_has_ponto_de_onibus_ponto_de_onibus1`
    FOREIGN KEY (`ponto_de_onibus_id`)
    REFERENCES `mydb`.`ponto_de_onibus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
